import { NextResponse } from "next/server";
import {
  getParagraph,
  getSection,
  getVerse,
  verseKey,
} from "@/lib/content";
import type { CompanionCitation, CompanionReply } from "@/lib/types";

interface CompanionRequest {
  paragraphId: string;
  question: string;
}

const MAX_QUESTION_LENGTH = 500;

export async function POST(req: Request) {
  let body: CompanionRequest;
  try {
    body = (await req.json()) as CompanionRequest;
  } catch {
    return NextResponse.json(
      { error: "Invalid JSON body." },
      { status: 400 },
    );
  }

  const paragraphId = typeof body.paragraphId === "string" ? body.paragraphId : "";
  const question = typeof body.question === "string" ? body.question.trim() : "";

  if (!paragraphId || !question) {
    return NextResponse.json(
      { error: "paragraphId and question are required." },
      { status: 400 },
    );
  }

  if (question.length > MAX_QUESTION_LENGTH) {
    return NextResponse.json(
      { error: `Question must be ${MAX_QUESTION_LENGTH} characters or fewer.` },
      { status: 400 },
    );
  }

  const paragraph = getParagraph(paragraphId);
  if (!paragraph) {
    return NextResponse.json(
      { error: "Unknown paragraph." },
      { status: 404 },
    );
  }

  const section = getSection(paragraph.sectionId);
  const citations: CompanionCitation[] = [
    {
      kind: "iqan",
      ref: `Kitáb-i-Íqán ¶${paragraph.index}`,
      excerpt: paragraph.text.slice(0, 220) + (paragraph.text.length > 220 ? "…" : ""),
    },
    ...paragraph.quranRefs
      .map((r) => {
        const v = getVerse(r.surah, r.ayah);
        if (!v) return undefined;
        return {
          kind: "quran" as const,
          ref: `Qur'an ${verseKey(v.surah, v.ayah)} (${v.surahName})`,
          excerpt: v.translation,
        };
      })
      .filter((c): c is CompanionCitation => Boolean(c)),
  ];

  const answerBody = [
    section
      ? `Paragraph ${paragraph.index} sits within the section "${section.title}" (Part ${paragraph.part}).`
      : `Paragraph ${paragraph.index} is in Part ${paragraph.part}.`,
    `Its rhetorical move is a ${paragraph.move}: ${paragraph.summary.bahai}`,
    paragraph.quranRefs.length > 0
      ? `The Qur'anic reference(s) surfaced here — ${paragraph.quranRefs
          .map((r) => `${r.surah}:${r.ayah}`)
          .join(", ")} — ground this move in the text of the Qur'an.`
      : "No direct Qur'anic verse is cited inside this paragraph; the reasoning here draws on the broader Qur'anic pattern of prophecy and recognition.",
  ].join(" ");

  const reply: CompanionReply = {
    answer: answerBody,
    citations,
    disclaimers: [
      "This companion is a stub. It is scoped to summarize the paragraph in context and surface its cited sources; it does not speculate beyond the text or its approved references.",
      "When the live model is wired in, responses will be generated by Claude with strict citation-only constraints and the same bounded source set (Shoghi Effendi's translation of the Íqán and Yusuf Ali's translation of the Qur'an, plus approved reference material).",
    ],
  };

  return NextResponse.json(reply);
}
